# Generated by Django 5.0 on 2024-08-05 06:55

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_quote_search_vector"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="quote",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="quotes_quot_search__829c7d_gin"
            ),
        ),
    ]
